### ISSUE TITLE
Thanks, everything works now

### ISSUE THREAD

**Issue by maxchepurko** [Robotics-Technology/Chess-Robot#7]
the robot starts moving behind the figures, but is immediately interrupted by an error with the words "O, wait":
1) MOVE UP
- Unknown status
- Unknown status
- Unknown status
- Unknown status
- Unknown status
- Issue detected
- Retrying
...

Experimentally found out that in the code of the file "ArmControl" :
# Check if they reached the requested position
while arrived == False and issue == 0:
bStat= base.GetStatus()
sStat = shoulder.GetStatus()
estate = elbow.GetStatus()
wStat = wrist.GetStatus()
gStat =gripper.GetStatus()

the "bStat" parameter takes the value "None". Maybe something is wrong with the database. What the error might be and how to fix it?

**Comment by geraldinebc** [comment]
This is probably due to a bad calibration.

Before using the program be sure to update the servo's firmware:
https://www.robotshop.com/products/lynxmotion-lss-configuration-software

And calibrate the arm using:
https://www.robotshop.com/products/lynxmotion-lss-lss-flowarm-app-download

Or, preferably, calibrate each servo separately using LSS Config.

For more details on the initial setup, visit:
https://community.robotshop.com/robots/show/chess-robot-set-up
